export const followupMessages = [
  {
    id: "m1",
    sender: "outgoing" as const,
    text: "היי נועה! אני ברוס מאקדמיית הלוחמים 😊\nאיך היה שיעור הניסיון אתמול?",
    timestamp: "10:03",
    status: "read" as const,
    delayBeforeMs: 600,
  },
  {
    id: "m2",
    sender: "incoming" as const,
    text: "היה כיף! האמת שהיה קצת מהיר בשבילי, אני די מתחילה ולא הצלחתי לעקוב בכל הקומבינות",
    timestamp: "10:18",
    delayBeforeMs: 3000,
  },
  {
    id: "m3",
    sender: "outgoing" as const,
    text: "תודה ששיתפת, נועה. וקודם כל — עצם זה שהגעת לאימון ראשון זה הצעד הכי גדול 💪",
    timestamp: "10:18",
    status: "read" as const,
    delayBeforeMs: 1200,
  },
  {
    id: "m4",
    sender: "outgoing" as const,
    text: "קומבינות זה משהו שהגוף לומד עם הזמן. אף אחד לא קולט אותן בשיעור הראשון — זה לא קשור אלייך, זה התהליך.",
    timestamp: "10:19",
    status: "read" as const,
    delayBeforeMs: 800,
  },
  {
    id: "m5",
    sender: "outgoing" as const,
    text: 'בדיוק בשביל זה יש לנו את קבוצת "יסודות" — שיעור איטי יותר שמפרק כל קומבינה מאפס, בלי לחץ.',
    timestamp: "10:19",
    status: "read" as const,
    delayBeforeMs: 1100,
  },
  {
    id: "m6",
    sender: "outgoing" as const,
    text: "רוצה לנסות שיעור יסודות בחינם? יש שני מועדים השבוע:\n• ראשון 18:00\n• רביעי 19:00",
    timestamp: "10:19",
    status: "read" as const,
    delayBeforeMs: 900,
  },
  {
    id: "m7",
    sender: "incoming" as const,
    text: "וואו, תודה!! ראשון 18:00 מעולה 🙌",
    timestamp: "10:23",
    delayBeforeMs: 2800,
  },
  {
    id: "m8",
    sender: "outgoing" as const,
    text: "שריינתי לך ✓ אשלח תזכורת ביום ראשון בבוקר.",
    timestamp: "10:23",
    status: "read" as const,
    delayBeforeMs: 1100,
  },
  {
    id: "m9",
    sender: "outgoing" as const,
    text: "בנוסף סימנתי לבעל הסטודיו שיכיר אותך אישית כשתגיעי 💪",
    timestamp: "10:23",
    status: "read" as const,
    delayBeforeMs: 900,
  },
];
