export const noShowMessages = [
  {
    id: "n1",
    sender: "outgoing" as const,
    text: "היי מיכל, לא ראינו אותך שבוע. הכל בסדר?",
    timestamp: "10:00",
    status: "read" as const,
    delayBeforeMs: 600,
  },
  {
    id: "n2",
    sender: "incoming" as const,
    text: "כן, סליחה... היה קצת קשה, ימים עם פחות שינה 😅",
    timestamp: "10:14",
    delayBeforeMs: 2200,
  },
  {
    id: "n3",
    sender: "outgoing" as const,
    text: "אאא, זה מתיש. אחרי שבוע כזה אי אפשר לצפות מעצמך לאימון.",
    timestamp: "10:14",
    status: "read" as const,
    delayBeforeMs: 1200,
  },
  {
    id: "n4",
    sender: "outgoing" as const,
    text: "כשתרגישי שחזרת לעצמך, אנחנו פה. אין ללחוץ.",
    timestamp: "10:14",
    status: "read" as const,
    delayBeforeMs: 1400,
  },
  {
    id: "n5",
    sender: "outgoing" as const,
    text: "אם תרצי, אפשר שאלכס ישוחח איתך קצת — לפעמים זה עוזר לחזור לשגרה. רוצה שיחזור אלייך?",
    timestamp: "10:14",
    status: "read" as const,
    delayBeforeMs: 1600,
  },
  {
    id: "n6",
    sender: "incoming" as const,
    text: "כן, אשמח",
    timestamp: "10:17",
    delayBeforeMs: 2400,
  },
  {
    id: "n7",
    sender: "outgoing" as const,
    text: "מצוין, סימנתי לו. הוא יחזור אלייך היום ✓",
    timestamp: "10:17",
    status: "read" as const,
    delayBeforeMs: 1000,
  },
];
