export const trialBookingMessages = [
  {
    id: "t1",
    sender: "incoming" as const,
    text: "היי! אתם עדיין פתוחים לשיעורי ניסיון?",
    timestamp: "22:48",
    delayBeforeMs: 600,
  },
  {
    id: "t2",
    sender: "outgoing" as const,
    text: "היי! אני יוגי, הבוט של סטודיו פראנה.\nמיכל תחזור אלייך מחר בבוקר, אבל בינתיים אני יכול לקבוע איתך שיעור ניסיון 😊",
    timestamp: "22:48",
    status: "read" as const,
    delayBeforeMs: 1000,
  },
  {
    id: "t3",
    sender: "incoming" as const,
    text: "מה הימים שנוחים השבוע?",
    timestamp: "22:48",
    delayBeforeMs: 1800,
  },
  {
    id: "t4",
    sender: "outgoing" as const,
    text: "יש לנו רביעי 08:00 (ויניאסה), חמישי 18:30 (האטה), שישי 09:00 (יוגה אנרגטית). מה הכי נוח?",
    timestamp: "22:48",
    status: "read" as const,
    delayBeforeMs: 900,
  },
  {
    id: "t5",
    sender: "incoming" as const,
    text: "רביעי בבוקר",
    timestamp: "22:49",
    delayBeforeMs: 2000,
  },
  {
    id: "t6",
    sender: "outgoing" as const,
    text: "מצוין. רק שם מלא וטלפון לאישור?",
    timestamp: "22:49",
    status: "read" as const,
    delayBeforeMs: 800,
  },
  {
    id: "t7",
    sender: "incoming" as const,
    text: "נועה כהן, 050-1234567",
    timestamp: "22:49",
    delayBeforeMs: 2200,
  },
  {
    id: "t8",
    sender: "outgoing" as const,
    text: "רשמתי אותך ✓ הוספתי את השיעור ליומן הסטודיו, ואשלח לך תזכורת ערב לפני. נתראה רביעי 08:00!",
    timestamp: "22:49",
    status: "read" as const,
    delayBeforeMs: 1100,
  },
];
