export const trialBookingMessages = [
  {
    id: "t1",
    sender: "incoming" as const,
    text: "היי! אתם עדיין פתוחים לשיעורי ניסיון?",
    timestamp: "22:47",
    delayBeforeMs: 600,
  },
  {
    id: "t2",
    sender: "outgoing" as const,
    text: "היי! אני אדרי, הבוט של הסטודיו.\nכן, אפשר לקבוע שיעור ניסיון — גם עכשיו 😊",
    timestamp: "22:47",
    status: "read" as const,
    delayBeforeMs: 1000,
  },
  {
    id: "t3",
    sender: "outgoing" as const,
    text: "מה הימים שנוחים לך בשבוע הקרוב?",
    timestamp: "22:47",
    status: "read" as const,
    delayBeforeMs: 800,
  },
  {
    id: "t4",
    sender: "incoming" as const,
    text: "אולי רביעי בבוקר?",
    timestamp: "22:48",
    delayBeforeMs: 2000,
  },
  {
    id: "t5",
    sender: "outgoing" as const,
    text: "מצוין! יש מקום ביום רביעי ב-08:00.\nמתאים?",
    timestamp: "22:48",
    status: "read" as const,
    delayBeforeMs: 900,
  },
  {
    id: "t6",
    sender: "incoming" as const,
    text: "כן, מושלם",
    timestamp: "22:48",
    delayBeforeMs: 1600,
  },
  {
    id: "t7",
    sender: "outgoing" as const,
    text: "נרשמת ✅\n\n📅 רביעי, 08:00\n📍 הרברט סמואל 15, ת״א\n\nתקבל תזכורת יום לפני. להתראות!",
    timestamp: "22:48",
    status: "read" as const,
    delayBeforeMs: 1100,
  },
];
