export const trialBookingMessages = [
  {
    id: "t1",
    sender: "incoming" as const,
    text: "שלום, אפשר לשמוע על שיעורי ניסיון?",
    timestamp: "22:48",
    delayBeforeMs: 600,
  },
  {
    id: "t2",
    sender: "outgoing" as const,
    text: "שלום! כן, אשמח 😊 יש לי שני מועדים השבוע — רביעי 08:00 וחמישי 18:30. מה מתאים?",
    timestamp: "22:48",
    status: "read" as const,
    delayBeforeMs: 1000,
  },
  {
    id: "t3",
    sender: "incoming" as const,
    text: "רביעי בבוקר. מה לובשים?",
    timestamp: "22:48",
    delayBeforeMs: 1800,
  },
  {
    id: "t4",
    sender: "outgoing" as const,
    text: "בגדי ספורט נוחים ובקבוק מים. יוגה-מאטס יש לנו.",
    timestamp: "22:48",
    status: "read" as const,
    delayBeforeMs: 900,
  },
  {
    id: "t5",
    sender: "incoming" as const,
    text: "מצוין, אני אגיע",
    timestamp: "22:49",
    delayBeforeMs: 1600,
  },
  {
    id: "t6",
    sender: "outgoing" as const,
    text: "מעולה! שם פרטי ומספר טלפון כדי לשמור לך מקום?",
    timestamp: "22:49",
    status: "read" as const,
    delayBeforeMs: 800,
  },
  {
    id: "t7",
    sender: "incoming" as const,
    text: "נועה כהן, 050-1234567",
    timestamp: "22:49",
    delayBeforeMs: 2200,
  },
  {
    id: "t8",
    sender: "outgoing" as const,
    text: "רשמתי ✓ מחכים לך רביעי ב-08:00. אשלח תזכורת ערב לפני.",
    timestamp: "22:49",
    status: "read" as const,
    delayBeforeMs: 1100,
  },
];
