export const waitlistMessages = [
  {
    id: "1",
    sender: "incoming" as const,
    text: "היי! יש מקום באימון מחר ב-07:00?",
    timestamp: "21:15",
    delayBeforeMs: 600,
  },
  {
    id: "2",
    sender: "outgoing" as const,
    text: "היי! אני אדרי, הבוט של סטודיו אדרנלין.\nשמח שפנית!",
    timestamp: "21:15",
    status: "read" as const,
    delayBeforeMs: 1200,
  },
  {
    id: "3",
    sender: "outgoing" as const,
    text: "האימון מחר ב-07:00 מלא כרגע (8/8 משתתפים).\nרוצה שאכניס אותך לרשימת המתנה?",
    timestamp: "21:15",
    status: "read" as const,
    delayBeforeMs: 900,
  },
  {
    id: "4",
    sender: "incoming" as const,
    text: "כן בבקשה, ממש מחפש משהו בבוקר",
    timestamp: "21:16",
    delayBeforeMs: 2200,
  },
  {
    id: "5",
    sender: "outgoing" as const,
    text: "הוספתי אותך לרשימה ✅\nאם מישהו מבטל — תקבל הודעה מיידית.",
    timestamp: "21:16",
    status: "read" as const,
    delayBeforeMs: 1100,
  },
  {
    id: "6",
    sender: "incoming" as const,
    text: "תודה",
    timestamp: "21:16",
    delayBeforeMs: 1800,
  },
  {
    id: "7",
    sender: "outgoing" as const,
    text: "בשורות טובות — נפתח מקום באימון מחר 07:00.\n\nהמקום שמור לך עד 23:30, אחרי זה עובר לבא בתור.\nמגיע?",
    timestamp: "23:14",
    status: "read" as const,
    delayBeforeMs: 3000,
  },
  {
    id: "8",
    sender: "incoming" as const,
    text: "בטח, מגיע!",
    timestamp: "23:15",
    delayBeforeMs: 2000,
  },
  {
    id: "9",
    sender: "outgoing" as const,
    text: "מעולה, רשום אותך ✅\n\n📅 מחר, 07:00\n📍 הרברט סמואל 15, ת״א\n\nלהגיע 5 דק׳ לפני. נתראה!",
    timestamp: "23:15",
    status: "read" as const,
    delayBeforeMs: 1200,
  },
];
